<div class="container">
<h1>Ny post</h1>
<form action="/post/store" method="POST" id="post-form">
<div class="input">
    <input type="text" name="title" value="" placeholder="Titel" data-validation="length alphanumeric" data-validation-length="min4" />
</div>
<div class="input">
    <textarea name="description" cols="40" rows="10" placeholder="Beskrivning"></textarea>
</div>
<button class="btn btn-success" type="submit">Spara</button>
<a href="/" class="btn btn-primary">Avbryt</a>
</form>
</div>
