<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MVC-provet</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
</head>
<body>
    <main>
        <?php require($this->getContent()) ?>        
    </main>
    <script src="//cdn.jsdelivr.net/jquery/1.12.4/jquery.min.js"></script>
    <script src="//cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
    <script src="/js/validator.js"></script>  
</body>
</html>